#!/bin/bash

ACCOUNT=$1;
shift;
SAVEIFS=$IFS;
IFS=$(echo -en "\n\b");

for file in $@;
do
    FILE_TYPE=`file -I $file | cut -d':' -f2 | cut -d';' -f1 | tr -d ' '`;
    if [ $FILE_TYPE != 'audio/mp4' ]; then
        continue;
    fi;
    CURRENT_ACCOUNT=`mp4info $file | grep 'iTunes Account:' | cut -d' ' -f4`;
    echo "current account for $file: $CURRENT_ACCOUNT";
    if [ $CURRENT_ACCOUNT == $ACCOUNT ]; then
        echo $file;
    fi;
done;
IFS=$SAVEIFS
