#!/usr/bin/perl

use warnings;
use strict;

use WWW::Curl::Easy;
die 'no url passed' unless scalar(@ARGV);
my $url = $ARGV[0];
my $count = 0;
while(1) {
    $count++;
    my $curl = WWW::Curl::Easy->new;

    $curl->setopt(CURLOPT_HEADER,1);
    $curl->setopt(CURLOPT_URL, $url);

    my $response_body;
    $curl->setopt(CURLOPT_WRITEDATA,\$response_body);
    my $retcode = $curl->perform;
    
    if ($retcode == 0) {
        my $response_code = $curl->getinfo(CURLINFO_HTTP_CODE);
        if($response_code =~ /2\d\d/) {
            print("site works: $url");
            print(chr(7) . chr(7) .chr(7) .chr(7) .chr(7));
            exit;
        }
    } else {
        print("An error happened: $retcode ".$curl->strerror($retcode)." ".$curl->errbuf."\n");
    }
    print STDERR "\rcount: $count";
    sleep(10);
}
